version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Prepare build enviorment
          command: |
            docker run --privileged linuxkit/binfmt:v0.6
            docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf
            docker cp buildkit:/usr/bin/buildctl /usr/bin/
            export BUILDKIT_HOST=tcp://0.0.0.0:1234

      - run:
          name: Build and push image
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            bash ./.build.sh
buildarm:
  docker:
    - image: debian:stretch
    
  steps:
    - checkout

    - setup_remote_docker:
        docker_layer_caching: true

    - run:
        name: Install Docker client
        command: |
          set -x
          VER="17.03.0-ce"
          curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          mv /tmp/docker/* /usr/bin

    - run:
        name: Prepare build enviorment
        command: |
          docker run --privileged linuxkit/binfmt:v0.6
          docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf
          docker cp buildkit:/usr/bin/buildctl /usr/bin/
          export BUILDKIT_HOST=tcp://0.0.0.0:1234

    - run:
        name: Build and push image
        command: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          bash ./.buildarm.sh
workflows:
  version: 2
  build_and_deploy:
    triggers:
      - schedule:
          cron: "0 9 * * 0"
          filters:
              branches:
                only:
                  - master
    jobs:
      - build
      - buildarm
