version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Prepare build enviorment
          command: |
            docker run --privileged linuxkit/binfmt:v0.6
            docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf
            docker cp buildkit:/usr/bin/buildctl /usr/bin/
            export BUILDKIT_HOST=tcp://0.0.0.0:1234

      - run:
          name: Build and push image
          command: |
            bash ./.build.sh
  "buildarm":
    machine: true

    steps:
      - checkout

      - run:
          name: Prepare build enviorment
          command: |
            docker run --privileged linuxkit/binfmt:v0.6
            docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf
            docker cp buildkit:/usr/bin/buildctl /usr/bin/
            export BUILDKIT_HOST=tcp://0.0.0.0:1234

      - run:
          name: Build and push image
          command: |
            bash ./.buildarm.sh
workflows:
  version: 2
  commit:
    jobs:
      - build
      - "buildarm"
  weekly:
    triggers:
      - schedule:
          cron: "0 9 * * 0"
          filters:
              branches:
                only:
                  - master
    jobs:
      - build
      - "buildarm"
