name: build

on: |
  push
  schedule:
    - cron:  '0 7 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Pre-requisites
      run: |
        docker run --privileged linuxkit/binfmt:v0.6
        docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf
        docker cp buildkit:/usr/bin/buildctl /usr/bin/
        export BUILDKIT_HOST=tcp://0.0.0.0:1234
    - name: Building and pushing ARM and AMD64 images
      run: |
        bash ./.build.sh
